// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgxeeairbvukecqomfwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxneGVlYWlyYnZ1a2VjcW9tZndqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgyMDU5MTYsImV4cCI6MjA4Mzc4MTkxNn0.KpHM5mbgfBd-abnZmPNlTQ9E20yC67Y6Rd7mSKJv5Uw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});